/**
 * Versioned Canonical Grocery Ontology (grocery.v1)
 * Version: 1.4
 * Supports Global & Indian Multilingual Lexicons with unique canonical IDs.
 */

export interface CanonicalGroceryItem {
  id: string; // Unique namespaced ID e.g. "grocery.vegetables.leek"
  canonical: string;
  category: string;
  default_unit: string;
  locale_names: Record<string, string>;
  aliases: string[];
  phonetic_markers: string[];
}

export const GROCERY_ONTOLOGY_VERSION = '1.4';

export const CANONICAL_GROCERY_ONTOLOGY: CanonicalGroceryItem[] = [
  // Fruits & Vegetables
  {
    id: 'grocery.vegetables.leek',
    canonical: 'Leek',
    category: 'Fruits & Vegetables',
    default_unit: 'pieces',
    locale_names: {
      'en-US': 'Leek',
      'en-IN': 'Leek',
      'hi-IN': 'Leek',
      'es-ES': 'Puerro',
      'fr-FR': 'Poireau',
      'de-DE': 'Lauch',
    },
    aliases: ['leeks', 'green leek', 'wild leek', 'puerro', 'poireau', 'lauch'],
    phonetic_markers: ['leak', 'leaks', 'leke', 'lique', 'lic'],
  },
  {
    id: 'grocery.vegetables.ginger',
    canonical: 'Ginger',
    category: 'Fruits & Vegetables',
    default_unit: 'pieces',
    locale_names: {
      'en-US': 'Ginger',
      'en-IN': 'Ginger (Adrak)',
      'hi-IN': 'Adrak',
      'es-ES': 'Jengibre',
      'fr-FR': 'Gingembre',
      'de-DE': 'Ingwer',
    },
    aliases: ['adrak', 'fresh ginger', 'ginger root', 'jengibre', 'gingembre', 'ingwer'],
    phonetic_markers: ['adventure', 'advent', 'adrak', 'adrakh', 'ginjer', 'gingr', 'adreck'],
  },
  {
    id: 'grocery.vegetables.garlic',
    canonical: 'Garlic',
    category: 'Fruits & Vegetables',
    default_unit: 'pieces',
    locale_names: {
      'en-US': 'Garlic',
      'en-IN': 'Garlic (Lahsun)',
      'hi-IN': 'Lahsun',
      'es-ES': 'Ajo',
      'fr-FR': 'Ail',
      'de-DE': 'Knoblauch',
    },
    aliases: ['lahsun', 'garlic cloves', 'garlic bulb', 'ajo', 'ail', 'knoblauch'],
    phonetic_markers: ['lehsun', 'lahsan', 'garlik', 'garlick'],
  },
  {
    id: 'grocery.vegetables.onion',
    canonical: 'Onion',
    category: 'Fruits & Vegetables',
    default_unit: 'kg',
    locale_names: {
      'en-US': 'Onion',
      'en-IN': 'Onion (Pyaz)',
      'hi-IN': 'Pyaz',
      'es-ES': 'Cebolla',
      'fr-FR': 'Oignon',
      'de-DE': 'Zwiebel',
    },
    aliases: ['onions', 'red onion', 'white onion', 'pyaz', 'kanda', 'cebolla', 'oignon', 'zwiebel'],
    phonetic_markers: ['piaz', 'piyaz', 'unions', 'unyon', 'onionz'],
  },
  {
    id: 'grocery.vegetables.potato',
    canonical: 'Potato',
    category: 'Fruits & Vegetables',
    default_unit: 'kg',
    locale_names: {
      'en-US': 'Potato',
      'en-IN': 'Potato (Aalu)',
      'hi-IN': 'Aalu',
      'es-ES': 'Patata',
      'fr-FR': 'Pomme de terre',
      'de-DE': 'Kartoffel',
    },
    aliases: ['potatoes', 'russet potato', 'baby potato', 'aalu', 'alu', 'batata', 'patata', 'pomme de terre', 'kartoffel'],
    phonetic_markers: ['aloo', 'allu', 'potatos', 'potatoe', 'potahto'],
  },
  {
    id: 'grocery.vegetables.tomato',
    canonical: 'Tomato',
    category: 'Fruits & Vegetables',
    default_unit: 'kg',
    locale_names: {
      'en-US': 'Tomato',
      'en-IN': 'Tomato (Tamatar)',
      'hi-IN': 'Tamatar',
      'es-ES': 'Tomate',
      'fr-FR': 'Tomate',
      'de-DE': 'Tomate',
    },
    aliases: ['tomatoes', 'cherry tomatoes', 'roma tomato', 'tamatar', 'tomate'],
    phonetic_markers: ['tamatr', 'tomatos', 'tomatoe', 'tomahto'],
  },
  {
    id: 'grocery.fruits.apple',
    canonical: 'Apple',
    category: 'Fruits & Vegetables',
    default_unit: 'pieces',
    locale_names: {
      'en-US': 'Apple',
      'en-IN': 'Apple (Seb)',
      'hi-IN': 'Seb',
      'es-ES': 'Manzana',
      'fr-FR': 'Pomme',
      'de-DE': 'Apfel',
    },
    aliases: ['apples', 'red apple', 'green apple', 'gala apple', 'fuji apple', 'seb', 'manzana', 'pomme', 'apfel'],
    phonetic_markers: ['aple', 'aples', 'appl', 'saeb'],
  },
  {
    id: 'grocery.fruits.banana',
    canonical: 'Banana',
    category: 'Fruits & Vegetables',
    default_unit: 'dozen',
    locale_names: {
      'en-US': 'Banana',
      'en-IN': 'Banana (Kela)',
      'hi-IN': 'Kela',
      'es-ES': 'Plátano',
      'fr-FR': 'Banane',
      'de-DE': 'Banane',
    },
    aliases: ['bananas', 'ripe bananas', 'kela', 'platano', 'plátano', 'banane'],
    phonetic_markers: ['banan', 'bannana', 'kayla', 'kelaa'],
  },
  {
    id: 'grocery.fruits.mango',
    canonical: 'Mango',
    category: 'Fruits & Vegetables',
    default_unit: 'pieces',
    locale_names: {
      'en-US': 'Mango',
      'en-IN': 'Mango (Aam)',
      'hi-IN': 'Aam',
      'es-ES': 'Mango',
      'fr-FR': 'Mangue',
      'de-DE': 'Mango',
    },
    aliases: ['mangoes', 'alphonso mango', 'aam', 'mango'],
    phonetic_markers: ['mangos', 'aam', 'mangoo'],
  },
  {
    id: 'grocery.fruits.avocado',
    canonical: 'Avocado',
    category: 'Fruits & Vegetables',
    default_unit: 'pieces',
    locale_names: {
      'en-US': 'Avocado',
      'en-IN': 'Avocado',
      'hi-IN': 'Avocado',
      'es-ES': 'Aguacate',
      'fr-FR': 'Avocat',
      'de-DE': 'Avocado',
    },
    aliases: ['avocados', 'hass avocado', 'aguacate', 'avocat'],
    phonetic_markers: ['avacado', 'avocato', 'advocado'],
  },
  {
    id: 'grocery.fruits.orange',
    canonical: 'Orange',
    category: 'Fruits & Vegetables',
    default_unit: 'pieces',
    locale_names: {
      'en-US': 'Orange',
      'en-IN': 'Orange (Santra)',
      'hi-IN': 'Santra',
      'es-ES': 'Naranja',
      'fr-FR': 'Orange',
      'de-DE': 'Orange',
    },
    aliases: ['oranges', 'fresh orange', 'santra', 'narangi', 'naranja'],
    phonetic_markers: ['ornge', 'orinj', 'ornges', 'orangez'],
  },
  {
    id: 'grocery.vegetables.carrot',
    canonical: 'Carrot',
    category: 'Fruits & Vegetables',
    default_unit: 'kg',
    locale_names: {
      'en-US': 'Carrot',
      'en-IN': 'Carrot (Gajar)',
      'hi-IN': 'Gajar',
      'es-ES': 'Zanahoria',
      'fr-FR': 'Carotte',
      'de-DE': 'Karotte',
    },
    aliases: ['carrots', 'fresh carrots', 'gajar', 'zanahoria', 'carotte', 'karotte'],
    phonetic_markers: ['carot', 'carrots', 'gaajar', 'karrot'],
  },
  {
    id: 'grocery.vegetables.cucumber',
    canonical: 'Cucumber',
    category: 'Fruits & Vegetables',
    default_unit: 'pieces',
    locale_names: {
      'en-US': 'Cucumber',
      'en-IN': 'Cucumber (Kheera)',
      'hi-IN': 'Kheera',
      'es-ES': 'Pepino',
      'fr-FR': 'Concombre',
      'de-DE': 'Gurke',
    },
    aliases: ['cucumbers', 'kheera', 'pepino', 'concombre', 'gurke'],
    phonetic_markers: ['cucumbr', 'keera', 'khira'],
  },
  {
    id: 'grocery.fruits.lemon',
    canonical: 'Lemon',
    category: 'Fruits & Vegetables',
    default_unit: 'pieces',
    locale_names: {
      'en-US': 'Lemon',
      'en-IN': 'Lemon (Nimbu)',
      'hi-IN': 'Nimbu',
      'es-ES': 'Limón',
      'fr-FR': 'Citron',
      'de-DE': 'Zitrone',
    },
    aliases: ['lemons', 'lime', 'limes', 'nimbu', 'limon', 'citron', 'zitrone'],
    phonetic_markers: ['lemn', 'neembu', 'nimbooda'],
  },
  {
    id: 'grocery.vegetables.spinach',
    canonical: 'Spinach',
    category: 'Fruits & Vegetables',
    default_unit: 'bunches',
    locale_names: {
      'en-US': 'Spinach',
      'en-IN': 'Spinach (Palak)',
      'hi-IN': 'Palak',
      'es-ES': 'Espinaca',
      'fr-FR': 'Épinards',
      'de-DE': 'Spinat',
    },
    aliases: ['baby spinach', 'palak', 'espinaca', 'épinards', 'spinat'],
    phonetic_markers: ['paalak', 'spinich', 'spinnach'],
  },
  {
    id: 'grocery.pantry.pulses',
    canonical: 'Pulses / Dal',
    category: 'Pantry & Staples',
    default_unit: 'kg',
    locale_names: {
      'en-US': 'Pulses / Lentils',
      'en-IN': 'Dal / Pulses',
      'hi-IN': 'Dal',
      'es-ES': 'Lentejas',
      'fr-FR': 'Lentilles',
      'de-DE': 'Linsen',
    },
    aliases: ['pulse', 'pulses', 'dal', 'daal', 'lentil', 'lentils', 'toor dal', 'moong dal', 'chana dal', 'lentejas'],
    phonetic_markers: ['dall', 'daal', 'puls', 'pulss'],
  },
  {
    id: 'grocery.dairy.cheese',
    canonical: 'Cheese',
    category: 'Dairy & Eggs',
    default_unit: 'packs',
    locale_names: {
      'en-US': 'Cheese',
      'en-IN': 'Cheese',
      'hi-IN': 'Cheese',
      'es-ES': 'Queso',
      'fr-FR': 'Fromage',
      'de-DE': 'Käse',
    },
    aliases: ['cheddar', 'mozzarella', 'cheese slices', 'queso', 'fromage', 'käse'],
    phonetic_markers: ['cheez', 'cheeze'],
  },
  {
    id: 'grocery.beverages.juice',
    canonical: 'Juice',
    category: 'Beverages',
    default_unit: 'bottles',
    locale_names: {
      'en-US': 'Juice',
      'en-IN': 'Juice',
      'hi-IN': 'Juice',
      'es-ES': 'Jugo',
      'fr-FR': 'Jus',
      'de-DE': 'Saft',
    },
    aliases: ['fruit juice', 'orange juice', 'apple juice', 'mango juice', 'jugo', 'jus', 'saft'],
    phonetic_markers: ['joos', 'jooce', 'juce'],
  },


  // Dairy & Eggs
  {
    id: 'grocery.dairy.milk',
    canonical: 'Milk',
    category: 'Dairy & Eggs',
    default_unit: 'liters',
    locale_names: {
      'en-US': 'Milk',
      'en-IN': 'Milk (Doodh)',
      'hi-IN': 'Doodh',
      'es-ES': 'Leche',
      'fr-FR': 'Lait',
      'de-DE': 'Milch',
    },
    aliases: ['whole milk', 'skim milk', 'toned milk', 'cow milk', 'doodh', 'dudh', 'leche', 'lait', 'milch'],
    phonetic_markers: ['malk', 'melk', 'milck', 'dood', 'dud'],
  },
  {
    id: 'grocery.dairy.eggs',
    canonical: 'Eggs',
    category: 'Dairy & Eggs',
    default_unit: 'dozen',
    locale_names: {
      'en-US': 'Eggs',
      'en-IN': 'Eggs (Ande)',
      'hi-IN': 'Ande',
      'es-ES': 'Huevos',
      'fr-FR': 'Oeufs',
      'de-DE': 'Eier',
    },
    aliases: ['egg', 'brown eggs', 'white eggs', 'free range eggs', 'anda', 'ande', 'huevos', 'oeufs', 'eier'],
    phonetic_markers: ['egs', 'eegs', 'aande', 'undaa', 'undae'],
  },
  {
    id: 'grocery.dairy.butter',
    canonical: 'Butter',
    category: 'Dairy & Eggs',
    default_unit: 'packs',
    locale_names: {
      'en-US': 'Butter',
      'en-IN': 'Butter (Makhan)',
      'hi-IN': 'Makhan',
      'es-ES': 'Mantequilla',
      'fr-FR': 'Beurre',
      'de-DE': 'Butter',
    },
    aliases: ['salted butter', 'unsalted butter', 'amul butter', 'makhan', 'mantequilla', 'beurre'],
    phonetic_markers: ['buttr', 'makkhan', 'maakhan', 'batter'],
  },
  {
    id: 'grocery.dairy.paneer',
    canonical: 'Paneer (Cottage Cheese)',
    category: 'Dairy & Eggs',
    default_unit: 'packs',
    locale_names: {
      'en-US': 'Paneer / Cottage Cheese',
      'en-IN': 'Paneer',
      'hi-IN': 'Paneer',
      'es-ES': 'Queso Paneer',
      'fr-FR': 'Fromage Paneer',
      'de-DE': 'Paneer Käse',
    },
    aliases: ['paneer', 'cottage cheese', 'fresh paneer', 'amul paneer'],
    phonetic_markers: ['panir', 'pneer', 'paner'],
  },
  {
    id: 'grocery.dairy.curd',
    canonical: 'Curd / Yogurt',
    category: 'Dairy & Eggs',
    default_unit: 'packs',
    locale_names: {
      'en-US': 'Yogurt',
      'en-IN': 'Curd (Dahi)',
      'hi-IN': 'Dahi',
      'es-ES': 'Yogur',
      'fr-FR': 'Yaourt',
      'de-DE': 'Joghurt',
    },
    aliases: ['curd', 'yogurt', 'yoghurt', 'greek yogurt', 'dahi', 'dahi cup', 'yogur', 'yaourt', 'joghurt'],
    phonetic_markers: ['dhai', 'dahee', 'yougurt', 'yogart'],
  },

  // Pantry & Staples
  {
    id: 'grocery.pantry.cooking_oil',
    canonical: 'Cooking Oil',
    category: 'Pantry & Staples',
    default_unit: 'liters',
    locale_names: {
      'en-US': 'Cooking Oil',
      'en-IN': 'Cooking Oil (Tel)',
      'hi-IN': 'Tel',
      'es-ES': 'Aceite de cocina',
      'fr-FR': 'Huile de cuisson',
      'de-DE': 'Speiseöl',
    },
    aliases: ['oil', 'vegetable oil', 'olive oil', 'sunflower oil', 'mustard oil', 'tel', 'sarson ka tel', 'aceite', 'huile', 'öl'],
    phonetic_markers: ['telugu', 'tail', 'tel', 'tael', 'oyle'],
  },
  {
    id: 'grocery.pantry.wheat_flour',
    canonical: 'Wheat Flour (Atta)',
    category: 'Pantry & Staples',
    default_unit: 'kg',
    locale_names: {
      'en-US': 'Wheat Flour',
      'en-IN': 'Atta (Wheat Flour)',
      'hi-IN': 'Atta',
      'es-ES': 'Harina de trigo',
      'fr-FR': 'Farine de blé',
      'de-DE': 'Weizenmehl',
    },
    aliases: ['atta', 'flour', 'wheat flour', 'chakki atta', 'aashirvaad atta', 'harina', 'farine', 'mehl'],
    phonetic_markers: ['flower', 'flouer', 'aata', 'aatha'],
  },
  {
    id: 'grocery.pantry.rice',
    canonical: 'Rice',
    category: 'Pantry & Staples',
    default_unit: 'kg',
    locale_names: {
      'en-US': 'Rice',
      'en-IN': 'Rice (Chawal)',
      'hi-IN': 'Chawal',
      'es-ES': 'Arroz',
      'fr-FR': 'Riz',
      'de-DE': 'Reis',
    },
    aliases: ['basmati rice', 'brown rice', 'white rice', 'chawal', 'arroz', 'riz', 'reis'],
    phonetic_markers: ['chaawal', 'chaval', 'ryce', 'ris'],
  },
  {
    id: 'grocery.pantry.lentils',
    canonical: 'Lentils / Dal',
    category: 'Pantry & Staples',
    default_unit: 'kg',
    locale_names: {
      'en-US': 'Lentils',
      'en-IN': 'Dal / Lentils',
      'hi-IN': 'Dal',
      'es-ES': 'Lentejas',
      'fr-FR': 'Lentilles',
      'de-DE': 'Linsen',
    },
    aliases: ['dal', 'daal', 'toor dal', 'moong dal', 'masoor dal', 'chana dal', 'lentils', 'lentejas', 'lentilles', 'linsen'],
    phonetic_markers: ['dall', 'dhal', 'toll dal', 'tur dal'],
  },
  {
    id: 'grocery.pantry.sugar',
    canonical: 'Sugar',
    category: 'Pantry & Staples',
    default_unit: 'kg',
    locale_names: {
      'en-US': 'Sugar',
      'en-IN': 'Sugar (Chini)',
      'hi-IN': 'Chini',
      'es-ES': 'Azúcar',
      'fr-FR': 'Sucre',
      'de-DE': 'Zucker',
    },
    aliases: ['white sugar', 'brown sugar', 'cane sugar', 'cheeni', 'shakkar', 'azúcar', 'sucre', 'zucker'],
    phonetic_markers: ['chini', 'shakar', 'shugar', 'sugr'],
  },
  {
    id: 'grocery.pantry.salt',
    canonical: 'Salt',
    category: 'Pantry & Staples',
    default_unit: 'packs',
    locale_names: {
      'en-US': 'Salt',
      'en-IN': 'Salt (Namak)',
      'hi-IN': 'Namak',
      'es-ES': 'Sal',
      'fr-FR': 'Sel',
      'de-DE': 'Salz',
    },
    aliases: ['table salt', 'sea salt', 'rock salt', 'namak', 'tata salt', 'sal', 'sel', 'salz'],
    phonetic_markers: ['namaak', 'solt', 'saalt'],
  },

  // Bakery & Snacks
  {
    id: 'grocery.bakery.bread',
    canonical: 'Bread',
    category: 'Bakery & Snacks',
    default_unit: 'packs',
    locale_names: {
      'en-US': 'Bread',
      'en-IN': 'Bread (Pav)',
      'hi-IN': 'Bread',
      'es-ES': 'Pan',
      'fr-FR': 'Pain',
      'de-DE': 'Brot',
    },
    aliases: ['white bread', 'brown bread', 'whole wheat bread', 'multigrain bread', 'pav', 'pan', 'pain', 'brot'],
    phonetic_markers: ['breadth', 'bred', 'breat', 'bredd', 'paav', 'breads'],
  },
  {
    id: 'grocery.bakery.cereal',
    canonical: 'Oats / Cereal',
    category: 'Bakery & Snacks',
    default_unit: 'packs',
    locale_names: {
      'en-US': 'Cereal / Oats',
      'en-IN': 'Oats / Cornflakes',
      'hi-IN': 'Oats',
      'es-ES': 'Cereales',
      'fr-FR': 'Céréales',
      'de-DE': 'Müsli',
    },
    aliases: ['oats', 'rolled oats', 'quaker oats', 'corn flakes', 'cereals', 'cereal', 'muesli'],
    phonetic_markers: ['serial', 'cerial', 'ots', 'oat'],
  },
  {
    id: 'grocery.bakery.chips',
    canonical: 'Potato Chips',
    category: 'Bakery & Snacks',
    default_unit: 'packs',
    locale_names: {
      'en-US': 'Potato Chips',
      'en-IN': 'Chips / Wafers',
      'hi-IN': 'Chips',
      'es-ES': 'Patatas fritas',
      'fr-FR': 'Chips',
      'de-DE': 'Chips',
    },
    aliases: ['chips', 'crisps', 'lays', 'kurkure', 'nachos', 'patatas fritas'],
    phonetic_markers: ['chipz', 'cheeps', 'chpis', 'cheep'],
  },

  // Beverages
  {
    id: 'grocery.beverages.tea',
    canonical: 'Tea / Chai',
    category: 'Beverages',
    default_unit: 'packs',
    locale_names: {
      'en-US': 'Tea',
      'en-IN': 'Tea (Chai)',
      'hi-IN': 'Chai Patti',
      'es-ES': 'Té',
      'fr-FR': 'Thé',
      'de-DE': 'Tee',
    },
    aliases: ['tea', 'black tea', 'green tea', 'chai', 'chai patti', 'tata tea', 'té', 'thé', 'tee'],
    phonetic_markers: ['chay', 'chaai', 'tea bags', 'te'],
  },
  {
    id: 'grocery.beverages.coffee',
    canonical: 'Coffee',
    category: 'Beverages',
    default_unit: 'packs',
    locale_names: {
      'en-US': 'Coffee',
      'en-IN': 'Coffee',
      'hi-IN': 'Coffee',
      'es-ES': 'Café',
      'fr-FR': 'Café',
      'de-DE': 'Kaffee',
    },
    aliases: ['instant coffee', 'nescafe', 'bru coffee', 'espresso', 'café', 'kaffee'],
    phonetic_markers: ['koffee', 'caffee', 'kafi'],
  },
  {
    id: 'grocery.beverages.water',
    canonical: 'Water',
    category: 'Beverages',
    default_unit: 'bottles',
    locale_names: {
      'en-US': 'Water',
      'en-IN': 'Mineral Water (Pani)',
      'hi-IN': 'Pani',
      'es-ES': 'Agua',
      'fr-FR': 'Eau',
      'de-DE': 'Wasser',
    },
    aliases: ['mineral water', 'bottled water', 'sparkling water', 'pani', 'paani', 'agua', 'eau', 'wasser'],
    phonetic_markers: ['watar', 'watter', 'paani', 'paney'],
  },

  // Personal Care
  {
    id: 'grocery.personal_care.toothpaste',
    canonical: 'Toothpaste',
    category: 'Personal Care',
    default_unit: 'packs',
    locale_names: {
      'en-US': 'Toothpaste',
      'en-IN': 'Toothpaste',
      'hi-IN': 'Toothpaste',
      'es-ES': 'Dentífrico',
      'fr-FR': 'Dentifrice',
      'de-DE': 'Zahnpasta',
    },
    aliases: ['colgate', 'sensodyne', 'close up', 'pepsodent', 'dentífrico', 'dentifrice', 'zahnpasta'],
    phonetic_markers: ['tooth paste', 'tutpaste', 'toothpast'],
  },
  {
    id: 'grocery.personal_care.soap',
    canonical: 'Bath Soap',
    category: 'Personal Care',
    default_unit: 'packs',
    locale_names: {
      'en-US': 'Bath Soap',
      'en-IN': 'Soap (Sabun)',
      'hi-IN': 'Sabun',
      'es-ES': 'Jabón',
      'fr-FR': 'Savon',
      'de-DE': 'Seife',
    },
    aliases: ['soap', 'body soap', 'dove soap', 'dettol soap', 'lux', 'jabón', 'savon', 'seife'],
    phonetic_markers: ['sope', 'sop', 'sabun', 'saabun'],
  },
];

export const ONTOLOGY_INDEX = new Map<string, CanonicalGroceryItem>();

CANONICAL_GROCERY_ONTOLOGY.forEach((item) => {
  ONTOLOGY_INDEX.set(item.id, item);
  ONTOLOGY_INDEX.set(item.canonical.toLowerCase(), item);
  item.aliases.forEach((a) => ONTOLOGY_INDEX.set(a.toLowerCase(), item));
});
